### ISSUE TITLE
多个视频的合集下载时只能下载第一个视频 

### ISSUE THREAD

**Issue by GaoHaHa-IronMan** [iuroc/bilidown#5]
视频链接：https://www.bilibili.com/video/BV1WR4y1E7ud/
![image](https://github.com/user-attachments/assets/aabc15d3-458e-419d-aa48-713ec18e4411)

**Comment by GaoHaHa-IronMan** [comment]
下载后视频内容只有只有P1

**Comment by iuroc** [comment]
暂未支持分集解析，下个版本会支持

**Comment by iuroc** [comment]
项目已重构，欢迎下载新版本使用。支持 8K 视频、Hi-Res 音频下载、批量解析，可扫码登录，常驻托盘。

**Comment by GaoHaHa-IronMan** [comment]
> 项目已重构，欢迎下载新版本使用。支持 8K 视频、Hi-Res 音频下载、批量解析，可扫码登录，常驻托盘。

我看release里没有mac版本的安装包，项目的介绍文档能不能添加怎么打包的教程。

**Comment by iuroc** [comment]
> > 项目已重构，欢迎下载新版本使用。支持 8K 视频、Hi-Res 音频下载、批量解析，可扫码登录，常驻托盘。
> 
> 我看release里没有mac版本的安装包，项目的介绍文档能不能添加怎么打包的教程。

构建流程请查看：https://github.com/iuroc/bilidown/blob/main/README_INIT.md

我是在 Windows 上打包的，通过 Goreleaser 工具交叉编译 Linux 和 Mac 时均出现问题，不得已就先构建了稳定的 Windows 版本。

如果你有 Mac 环境，请改动一下[.goreleaser.yaml](https://github.com/iuroc/bilidown/blob/main/server/.goreleaser.yaml)，将 
`darwin` 选项的注释去掉。

构建时如果遇到问题，请及时向我反馈，谢谢。
 
```yaml
builds:
    - env:
          - CGO_ENABLED=1
      goos:
          - windows
          - darwin  //// 将这个选项打开
```
